version: "3.8"

services:

  db:
    container_name: postgresql
    image: postgres:12.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host ${HOST} --port ${PORT} --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    environment:
      - DB_URI=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - HOST=${HOST}
      - PORT=${PORT}